{% set name = "rkstiff" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b00978be213c0f31d68f98b9fef88d71e0b4b788c0c3c227bb5df049fd9204f8

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.14.0
    - scipy >=1.3.2

test:
  imports:
    - rkstiff
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/whalenpt/rkstiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runge-Kutta adaptive-step solvers for nonlinear PDEs
  description: |
    Adaptive-step Runge-Kutta integrating-factor and 
    exponential time-differencing solvers for nonlinear PDES 
    of the form dtU = LU+NL(U). For use with Python 3.5+.
  dev_url: https://github.com/whalenpt/rkstiff

extra:
  recipe-maintainers:
    - whalenpt
